### ISSUE TITLE
python_subpackage's urls.py contains blank urlconf entry causing invalid syntax

### ISSUE THREAD

**Issue by nam20485** [hackoregon/2019-backend-cookiecutter-django#1]
https://github.com/hackoregon/2019-backend-cookiecutter-django/blob/88071a3366cbff00a815eb5881e881fd0d901f6d/%7B%7Bcookiecutter.github_repo%7D%7D/%7B%7Bcookiecutter.python_package_namespace%7D%7D/%7B%7Bcookiecutter.python_subpackage%7D%7D/urls.py#L15

Blank urlconf entry should be removed.

**Comment by bhgrant8** [comment]
Thanks. corrected in local branch, will be in next PR.
