### ISSUE TITLE
Required changes for the files that land in "bin/"

### ISSUE THREAD

**Issue by znmeb** [hackoregon/2019-backend-cookiecutter-django#10]
There are two changes that need to be applied to the files that land in the project `bin` directory:

1. They need to be executable. That is, they either need to be marked `chmod +x` in the template or they need to have that done while creating the repo from the template.
2. All `docker` and `docker-compose` commands need to be preceded by `sudo`. On some Linux systems, this is necessary for security reasons, and it's considered to be a best practice everywhere, rather than using the `docker` group to avoid it.

**Comment by bhgrant8** [comment]
1. - this should be fixed via: https://github.com/hackoregon/2019-backend-cookiecutter-django/commit/f6edd493f1ee247e216bb4e24fff6afec3fd6c38
ran a `chmod +x ./bin/*.sh` prior to commit.
2. ok, let's add

**Comment by bhgrant8** [comment]
2 should be fixed via:
https://github.com/hackoregon/2019-backend-cookiecutter-django/commit/34167559ebe71f33e9e386a0f0d5cf783a5b47f8

**Comment by bhgrant8** [comment]
Issues should be resolved via #23 going to close this ticket
