### ISSUE TITLE
Add a Standards Documentation to Template

### ISSUE THREAD

**Issue by bhgrant8** [hackoregon/2019-backend-cookiecutter-django#15]
## Detailed Description

Add documentation to this template regarding hack oregon standards for api development. standards to be decided through platform request 

## Context

This is important to specify standards for future users of api

## Possible Implementation

Provide a "Standards" readme, including examples

## Your Environment

n/a

**Comment by bhgrant8** [comment]
Commit: https://github.com/hackoregon/2019-backend-cookiecutter-django/commit/2c930f51e2c96083de9023921aee72a79e5b11ec

provides a first pass at providing this

**Comment by znmeb** [comment]
It looks good - the only question I have is whether it accounts for "legacy" databases where the column names might not conform to the Django ORM conventions on field names. When I build our databases I made all the columns lower case alpha with underscore separators, but that process was an extra step - the column names were upper case in the data we got from TriMet.

**Comment by bhgrant8** [comment]
> It looks good - the only question I have is whether it accounts for "legacy" databases where the column names might not conform to the Django ORM conventions on field names. When I build our databases I made all the columns lower case alpha with underscore separators, but that process was an extra step - the column names were upper case in the data we got from TriMet.

DRF also allows you to set the field name via the serializer, using a source field.

For example let's say your model looks as follows:

```python
class Park(models.Model):
    name = models.CharField(max_length=256)
    Alternate_Name = models.CharField(max_length=256, blank=True)
    objects = models.GeoManager()

    class Meta:
        db_table = u'p_park'

```

and you wanted to call the "alternate_name" field "location"

```python
class ParkSerializer(serializers.ModelSerializer):
    parkLocation = serializers.SomeSerializerField(source='Alternate_Name')

    class Meta:
        model = Park
        fields = ('other_fields', 'parkLocation')
```

"SomeSerializerField"  would be the actual field type as per: https://www.django-rest-framework.org/api-guide/fields/

**Comment by nam20485** [comment]
You can also specify to use a different field name than the DB column's name directly using a parameter to the Field object's constructor:

https://docs.djangoproject.com/en/2.2/ref/models/fields/#db-column

**Comment by bhgrant8** [comment]
closing with: https://github.com/hackoregon/2019-backend-cookiecutter-django/pull/24
