### ISSUE TITLE
{{cookiecutter.github_repo}}/bin/build.sh's -d docker-compose command needs reference to docker image's service name

### ISSUE THREAD

**Issue by nam20485** [hackoregon/2019-backend-cookiecutter-django#2]
Running `bin/build.sh -d` results in syntax error:

```
nam20485@mint182 ~/src/hackoregon/2019-sandbox-backend $ bin/build.sh -d
ERROR: Need service name for --build-arg option
```

Due to `--build-arg` argument requiring the service name from the docker image as specified in the docker-compose.yml.

Corrected example of build.sh: https://github.com/hackoregon/2019-sandbox-backend/blob/5e9459c26536d40d1ebc148fe7b17c5dfbb10453/bin/build.sh#L9

Which matches the service name in my docker-compose.yml: https://github.com/hackoregon/2019-sandbox-backend/blob/5e9459c26536d40d1ebc148fe7b17c5dfbb10453/docker-compose.yml#L3

In my repo, you can see this should be `api` since that is what I specified for my `{{cookiecutter.python_subpackage}}`, since I believe that is what caused my service to be named `api`. Either that or you hard-coded the service name to be api.

At any rate the cookiecutter template's build.sh needs to be modified to add the service name.

**Comment by bhgrant8** [comment]
Yeah it seems that either certain OS's or perhaps versions of docker? require the service, but I never had run into this in my development.

I did hardcode 'api' as the docker service name in the compose, so think this is where it is pulling"
https://github.com/hackoregon/2019-backend-cookiecutter-django/blob/de3f4d34825ffd15490b8e8165dabbe5204e47d7/%7B%7Bcookiecutter.github_repo%7D%7D/docker-compose.yml#L3

So guess we can just hardcode into the build.sh as well? 
Can we think of any reason to not hardcode as 'api'?

**Comment by bhgrant8** [comment]
fixed with linked PR
