### ISSUE TITLE
`.travis.yml` defaults to ruby because no language is specified, but missing rakefile causes build to fail

### ISSUE THREAD

**Issue by nam20485** [hackoregon/2019-backend-cookiecutter-django#3]
From [Tavis build #19](https://travis-ci.org/hackoregon/2019-sandbox-backend/builds/537007743):

```
$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
The command "rake" exited with 1.
```

**Comment by bhgrant8** [comment]
Current .travis is definitely not functioning, so will need some updates. I've been imagining the following as a deploy path:

![Django Rest Framework, API Development, and Tooling](https://user-images.githubusercontent.com/26581237/58371001-0be7b300-7ec2-11e9-8e4c-2f07786df392.png)

So if we agree as an organization:

will have to add in the different parts to travis
confirm any variables which need to be set
whether to use travis deployers (https://docs.travis-ci.com/user/deployment)
what we need to script (or could pull from last year)
test a deploy

**Comment by BrianHGrant** [comment]
Going to close out this ticket, and open new enhancement request regarding adding a travis file
