### ISSUE TITLE
Add Local Development Database option

### ISSUE THREAD

**Issue by bhgrant8** [hackoregon/2019-backend-cookiecutter-django#30]
## Detailed Description

Add an option to run a local development database within the docker compose and associated files
## Context

to aid developers in local work
## Your Environment

* Version (https://github.com/hackoregon/2019-backend-cookiecutter-django/releases): 
* Operating System and version:
* Link to your project:

**Comment by znmeb** [comment]
We're discussing this in Slack and I think the consensus is it's no longer necessary. So I'm closing it - reopen if any wants it.
