### ISSUE TITLE
Swagger Schema View Returning "Could not satisfy the request Accept header." 

### ISSUE THREAD

**Issue by geophpherie** [hackoregon/2019-backend-cookiecutter-django#34]
## Description of problem

Swagger UI won't return schema JSON with current `get_swagger_view` in `urls.py`

## Steps to Reproduce the Problem

1. Create Project, run application.
2. Navigate to `schema` URL.
3. "Try-It-Out" --> "Execute" under `schema`

## Expected Behavior

I expected to see a JSON formatting of the API schema.

## Actual Behavior

406: Undocumented Error:
`
{
  "detail": "Could not satisfy the request Accept header."
}
`

## Logs/Screenshots

Here's the error.

<img width="1434" alt="Screen Shot 2019-06-02 at 11 00 57 PM" src="https://user-images.githubusercontent.com/19380579/58780298-70270880-858d-11e9-92ca-705eb618b185.png">

## Related Code

Code is from cookiecutter template.

## Specifications

  - Version (https://github.com/hackoregon/2019-backend-cookiecutter-django/releases): 0.1.0?
  - Platform (Your Host OS): MacOS
  - Project Repo: [repo](https://github.com/hackoregon/2019-transportation-systems-backend)

## Any idea of problem? What to do to fix?

The issue is that the Swagger client sets the header to `application/json` but the API provides `application/coreapi+json` (or some combo of those, not sure of the right terms). Regardless, the `get_swagger_view` needs to be re-defined to provide a `application/json` response header. The solution is a direct copy of [here](https://github.com/marcgibbons/django-rest-swagger/issues/701#issuecomment-336737079).

## Anything to add?
After implementing this fix, I see the following, which looks correct to me. 
<img width="1427" alt="Screen Shot 2019-06-02 at 11 06 23 PM" src="https://user-images.githubusercontent.com/19380579/58780588-3b678100-858e-11e9-954c-73633c6f23a8.png">

I'm happy to open this as a PR, I'm just not aware of the implications of editing the `get_swagger_view` in this fashion.

**Comment by bhgrant8** [comment]
should be fixed via:
https://github.com/hackoregon/2019-backend-cookiecutter-django/commit/eafb794fc9df484dd28b05ccc35a2e869e4cd169
