### ISSUE TITLE
Add instructions for ccokiecutter set up to include step to go to GitHub and add repo first.

### ISSUE THREAD

**Issue by unstasis** [hackoregon/2019-backend-cookiecutter-django#36]
## Your Environment

* Version (https://github.com/hackoregon/2019-backend-cookiecutter-django/releases): 
* Operating System and version:
* Link to your project:

**Comment by unstasis** [comment]
Also add optional data science web site on that line.

**Comment by bhgrant8** [comment]
added info via commit: https://github.com/hackoregon/2019-backend-cookiecutter-django/commit/8d6391ef20a606b512d4913de41b7ebc952442fc
