### ISSUE TITLE
Need to add missing standard environment variables to env.sample

### ISSUE THREAD

**Issue by nam20485** [hackoregon/2019-backend-cookiecutter-django#4]
The following environment variables are used in various and multiple places in the cookiecutter templates' files but are not present in the env.sample file included in the generated repo.

```
DJANGO_SECRET_KEY=h0drjn265jn0f5T
POSTGRES_PORT=5432
DEBUG=True
```

If they are used in the template's files, they should be represented in the env.sample file.

**Comment by bhgrant8** [comment]
Thanks for catching. Have now updated in my local branch, and will be in next pr. so will close out.

**Comment by znmeb** [comment]
You also need to add `PROJECT_NAME` - it's in `docker-compose.yml`. Or remove it from `docker-compose.yml` if it's not referenced!

**Comment by bhgrant8** [comment]
think we will remove it, don't think project references anywhere but will double check.

**Comment by znmeb** [comment]
I removed it in the 2019-transportation-backend and everything seems to be working.

**Comment by bhgrant8** [comment]
Removed `PROJECT_NAME` from the docker-compose as not currently used. going to close this back out
