### ISSUE TITLE
{{cookiecutter.python_subpackage}}.urls not being imported and served from 2019-backend-docker image

### ISSUE THREAD

**Issue by nam20485** [hackoregon/2019-backend-cookiecutter-django#6]
I see that the 2019-backend-docker image's Django project is supposed to serve the {{cookiecutter.python_subpackage}}'s (Django app's) endpoints via this mechanism: https://github.com/hackoregon/2019-backend-docker/blob/da6543983623af5aa58f1c2bb079d54b4a6fbc45/backend/urls.py#L20.

Therefor, when I navigate to the base url of the image, I should see the /admin endpoint served, and since I have the following endpoints defined in the {{cookiecutter.python_subpackage}} (see https://github.com/hackoregon/2019-sandbox-backend/blob/master/hackoregon_sandbox/api/urls.py) I should see also /api and /schema endpoints served as well, if I understand correctly. 

However, when I spin up the container, I only see the /admin endpoint, which is served from the 2019-backend-docker, and neither of the endpoints server from the sub_package.

**Comment by znmeb** [comment]
Jeff Beyer and I are working on the Transportation API this weekend. Our repo is 2019-transportation-backend. Is there anything we need to change there?

**Comment by nam20485** [comment]
I made some progress on this front. Adding a copy of my urls.py into the local_settings directory allowed the docker backend to import the URLs and now my view endpoints are being found and served correctly. I actually used a symbolic link to the original copy under api directory placed into the local_settings directory.

**Comment by bhgrant8** [comment]
SEE PR: https://github.com/hackoregon/2019-backend-cookiecutter-django/pull/11
for potential fix

**Comment by BrianHGrant** [comment]
Has been fixed and merged to master. Closing out
